application: dart-lang
version: CHANGEME
# NOTE: URL is CHANGEME.dart-lang.appspot.com
#       To get your own staging server, change 'CHANGEME' to... you guessed it.
#       To deploy to dartlang.org (only from a clean master workspace)
#       change CHANGEME to a date string: YYYY-MM-DD.
#       For more information on making changes, see goto/dartsiteupdate.
#
# IMPORTANT: AFTER changing the version, DO THIS:
#       make clean
#       make build

runtime: python
api_version: 1

#default_expiration: "1d"

handlers:

- url: /news.*
  script: scripts/redirector.py

- url: /atom.xml
  script: scripts/redirector.py

- url: /docs/api/.*
  script: scripts/redirector.py

- url: /(.*\.png)
  static_files: static/\1
  expiration: 4h
  upload: static/(.*\.png)
    
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static
