application: dart-lang
version: yourname-bfce4b5c8892ea682db257c3540aa4ac
# NOTE: URL is yourname-bfce4b5c8892ea682db257c3540aa4ac.dart-lang.appspot.com
#       To get your own staging server, change 'yourname' to... you guessed it.
#       To deploy to dartlang.org (only from a clean master workspace)
#       remove everything up to and including the '-'.
#       For more information on making changes, see goto/dartsiteupdate.
#
# IMPORTANT: AFTER changing the version, DO THIS:
#       make clean
#       make build

runtime: python
api_version: 1

#default_expiration: "1d"

handlers:

- url: /docs/api/.*
  script: scripts/api-redirect.py

- url: /(.*\.png)
  static_files: static/\1
  expiration: 1h
  upload: static/(.*\.png)
    
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static
