application: dart-lang
version: bfce4b5c8892ea682db257c3540aa4ac
runtime: python
api_version: 1

#default_expiration: "1d"

handlers:
    
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static
