application: google.com:spotlang-org
version: dev
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
    
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static
